This is fine
sequelize/website pull request #255
Opened 2022-09-10 22:04 UTC by davidjss04

According to the API documentation it should be like this

2022-09-16 20:58 UTC, fzn0x approved these changes

2022-09-17 09:28 UTC, ephys commented
The previous version is actually valid in v6, but not recommended. We're dropping in as part of https://github.com/sequelize/sequelize/pull/14505. Good change 👍️

2022-09-17 09:29 UTC, ephys requested changes

2022-09-17 09:29 UTC, ephys commented on versioned_docs/version-6.x.x/other-topics/other-data-types.md
> +    })
Identation issue:

```suggestion
    type: DataTypes.ENUM({
      values: ['active', 'pending', 'deleted']
    }),
```

or for a terser version:

```suggestion
    type: DataTypes.ENUM(['active', 'pending', 'deleted']),
```

2022-10-19 12:31 UTC, davidjss04 commented
Thanks

2022-10-19 12:31 UTC, closed without merging