docs: Add sequelize-create-with-associations to resources
sequelize/website pull request #499
Opened 2023-06-16 14:30 UTC by roy-coder

Adding `@hatchifyjs/sequelize-create-with-associations` to the resource page

2023-06-17 12:52 UTC, ephys requested changes
The link leads to a 404 for me. Also don't forget to add it to the same page for v6 :)

2023-06-20 06:35 UTC, ephys requested changes

2023-06-20 06:35 UTC, ephys commented on versioned_docs/version-6.x.x/other-topics/resources.md
> +* [@hatchifyjs/sequelize-create-with-associations](https://github.com/bitovi/sequelize-create-with-associations) - More elegant update or create
This description from their repo is more precise I think:

```suggestion
* [@hatchifyjs/sequelize-create-with-associations](https://github.com/bitovi/sequelize-create-with-associations) - Automatically creates, bulkCreates and updates records that have relationships to each other without extra code.
```

2023-06-20 06:38 UTC, ephys commented
By the way that's pretty cool. It is something I want to change in sequelize, see https://github.com/sequelize/sequelize/issues/15233

2023-06-20 12:41 UTC, WikiRik approved these changes

2023-06-20 13:44 UTC, ephys approved these changes

2023-06-20 15:05 UTC, merged